### ISSUE TITLE
[BUG] Animist's Fury enchant provides no stats.

### ISSUE THREAD

**Issue by raethkcj** [ClassicWoWCommunity/sod-bugs#19]
#### 1.1. Description
  The [enchantment](https://wago.tools/db2/SpellItemEnchantment?build=1.15.4.56817&sort[ID]=desc&filter[ID]=7615&page=1) currently applies spell [468323](https://www.wowhead.com/classic/spell=468323), when it looks like it is intended to apply the aura [468320](https://www.wowhead.com/classic/spell=468320)
  
  #### 1.2. How to Reproduce
           1. On a druid with no enchants applied, note your stats
           2. Apply an [Animist's  Fury](https://www.wowhead.com/classic/item=231357/animists-fury) to your Head or Legs
           3. Observe your stats do not change
#### 2.1. Description
  Applying the enchant should increase your stats by the amount stated in the tooltip.

**Comment by AidanZMoon** [comment]
Fix for this sent to our internal realms for testing. Doing an audit on all of the other enchants now
