### ISSUE TITLE
[BUG] Is Amberseal Keeper Supposed to be This Bright?

### ISSUE THREAD

**Issue by Frankensteak** [ClassicWoWCommunity/sod-bugs#5]
#### 1.2. How to Reproduce
           1. Equip Amberseal Keeper in Dressing Room
           2. See how bright it is
  #### 1.3  Source Material
{Video, Posts, etc..}
#### 2.1. Weapon is not as bright

![image](https://github.com/user-attachments/assets/6be80f63-43a5-48b4-be65-5f6140bfc276)

**Comment by raethkcj** [comment]
![image](https://github.com/user-attachments/assets/77aafda1-5879-4bc0-93ce-90827e30a7c7)
